# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json

$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: en-US,de-DE

ignorePaths:
  - .git/*/**
  - .git/!(COMMIT_EDITMSG)
  - .vscode
  - .clangformat
  - vcpkg.json
  - '*.lock'
  - '*.log'
  - '*.json'
  - cspell.json
  - cspell*.{json,yaml}
  - /build-tools
  - /dependencies
  - /vcpkg_packages
  - /src/ShareCode.cpp
  - /src/steamapi/steamapi.cpp
dictionaryDefinitions:
  - name: repo-words
    addWords: true
    scope:
      - workspace
    path: ./repo-words.txt
    description: A list of words related to this repository.
dictionaries:
  - repo-words
languageSettings:
  - languageId: '*'
    allowCompoundWords: false
